version: "3"
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: "/app"
    tty: true
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: jupyter-lab --ip 0.0.0.0 --port=8080 --allow-root --no-browser
