version: "3"
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: "/app"
    tty: true
    volumes:
      - .:/app
    ports:
      - "8080:8080"
